on:
  pull_request:
    branches: [master]
    types: [closed]
name: Build and Publish Front End Part
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 2

      - name: Instal Dependencies
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install --frozen-lockfile

      - name: Build Project
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: build:prod

      - name: List output files
        run: find build/ -print

      - name: FTP-Deploy-Action
        uses: sebastianpopp/ftp-action@releases/v2
        with:
          host: ${{ secrets.FTP_SERVER }}
          user: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          localDir: "build"
